export declare const miaoRouteRules: {
    readonly help: RegExp;
    readonly calendar: RegExp;
    readonly profileList: RegExp;
    readonly profileDetail: RegExp;
    readonly artifactList: RegExp;
    readonly trainingStat: RegExp;
    readonly rankList: RegExp;
    readonly groupTop: RegExp;
    readonly rankAdmin: RegExp;
    readonly roleCombat: RegExp;
    readonly hardChallenge: RegExp;
    readonly charWiki: RegExp;
    readonly strategy: RegExp;
    readonly banner: RegExp;
    readonly gachaDetail: RegExp;
    readonly gachaStat: RegExp;
    readonly abyss: RegExp;
    readonly abyssStat: RegExp;
    readonly abyssUsage: RegExp;
    readonly todayMaterial: RegExp;
    readonly avatarCard: RegExp;
    readonly avatarWife: RegExp;
    readonly profileImgManage: RegExp;
    readonly admin: RegExp;
};
