import type React from 'react';
import URL_BG01 from '@src/assets/common/bg-01.jpg';
import URL_CARD_BG from '@src/assets/common/card-bg.png';
import URL_CROWN from '@src/assets/common/crown.png';
import URL_STAT_ICON from '@src/assets/common/icon.png';
import URL_FETTER from '@src/assets/common/item/fetter.png';
import URL_MAIN01 from '@src/assets/common/main-01.png';
import URL_MARK_ICON from '@src/assets/common/mark-icon.png';
export { URL_BG01, URL_CARD_BG, URL_CROWN, URL_FETTER, URL_MAIN01, URL_MARK_ICON, URL_STAT_ICON };
export declare const ELEM_BG: Record<string, string>;
export declare const ELEMENT_COLORS: Record<string, string>;
export declare const STAR_COLORS: Record<number, string>;
export declare const RARITY_COLORS: Record<number, string>;
export declare const CONS_COLORS: Record<number, string>;
export declare const CONS_SUFFIX: Record<string, string>;
export declare const GAME_ACCENT: Record<string, string>;
export declare const DARK_BG = "linear-gradient(180deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)";
export declare function contStyle(extra?: React.CSSProperties): React.CSSProperties;
export declare function contTitleStyle(extra?: React.CSSProperties): React.CSSProperties;
export declare function fetterStyle(level: number, size?: number): React.CSSProperties;
export declare function statIconStyle(key: string): React.CSSProperties;
export declare function rankIconStyle(type: 'dmg' | 'mark'): React.CSSProperties;
export declare const FONT_FAMILY = "\"HYWH\", \"tttgbnumber\", \"PingFang SC\", system-ui, sans-serif";
export declare const FONT_NZBZ = "\"NZBZ\", \"HYWH\", \"tttgbnumber\", system-ui, sans-serif";
export declare function formatDate(): string;
export declare function formatDateZh(): string;
