name: 基础推送检验

on:
  push:
    branches:
      - main
      - dev-*
      - test-*
      - for/dev-*
  workflow_dispatch:
    inputs:
      version:
        description: '版本号(自增)'
        required: false
      runner-type:
        description: '选择运行器类型'
        required: false
        default: 'self-hosted'
        type: choice
        options:
          - self-hosted
          - macos-latest
          - ubuntu-latest

jobs:
  build-to-deploy:
    runs-on: ${{ github.event.inputs.runner-type || 'self-hosted' }}

    steps:
      - name: 检出代码库
        uses: actions/checkout@v4

      - name: 设置nodejs版本
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 缓存游戏依赖
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-root-${{ hashFiles('yarn.lock') }}

      - name: 检查yarn工具
        run: |
          if ! command -v yarn &> /dev/null; then
             npm install -g yarn
          fi

      - name: 安装游戏依赖
        run: |
          yarn install --ignore-engines --frozen-lockfile

      - name: 打包测试
        run: |
          yarn build || echo "build 脚本执行失败或不存在"
